import React from "react";
import {
  FaRegFileAlt,
  FaStream,
  FaStar,
  FaGopuram,
  FaPodcast,
  FaFileSignature,
  FaBell,
  FaShoppingBag,
  FaWallet,
  FaHome,
  FaUserEdit,
  FaAdversal,
  FaStore,
  FaUsers,
  FaCircle,
  FaCog,
  FaQuestionCircle,
  FaSlidersH,
  FaUser,
  FaShoppingCart,
  FaGift,
} from "react-icons/fa";
import * as Icon from "react-feather";
import { BsImage } from "react-icons/bs";
import { TbTruckDelivery } from "react-icons/tb";
import { AiFillBell } from "react-icons/ai";
import { FiBarChart2 } from "react-icons/fi";

// eslint-disable-next-line no-sparse-arrays
const navigationConfig = [
  {
    id: "dashboard",
    title: "DASHBOARD",
    type: "item",
    icon: <FaHome size={15} />,
    permissions: ["admin", "editor"],
    navLink: "/Dash",
  },
  {
    type: "groupHeader",
    groupTitle: "PRODUCT MANAGEMENT",
  },
  {
    id: "order",
    title: "Orders",
    type: "collapse",
    icon: <FaShoppingCart color="blue" size={15} />,
    children: [
      {
        id: "all",
        title: "All",
        type: "item",
        icon: <FaCircle color="green" size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/order/all",
      },
      {
        id: "pending",
        title: "Pending",
        type: "item",
        icon: <FaCircle color="yellow" size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/order/pending",
      },
      {
        id: "confirmed",
        title: "Confirmed",
        type: "item",
        icon: <FaCircle color="green" size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/order/confirmed",
      },
      {
        id: "packaging",
        title: "Packaging",
        type: "item",
        icon: <Icon.Box color="blue" size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/order/packaging",
      },
      {
        id: "outfordelivery",
        title: "Out for delivery",
        type: "item",
        icon: <Icon.Package color="green" size={12} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/order/outfordelivery",
      },
      {
        id: "delivered",
        title: "Delivered",
        type: "item",
        icon: <FaCircle color="green" size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/order/delivered",
      },
      {
        id: "return",
        title: "Returned",
        type: "item",
        icon: <Icon.Package color="red" size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/order/returned",
      },
      {
        id: "failedtodeliver",
        title: "Failed to Deliver",
        type: "item",
        icon: <FaCircle color="red" size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/order/failedtodeliver",
      },
      {
        id: "canceled",
        title: "Canceled",
        type: "item",
        icon: <Icon.List color="red" size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/order/canceled",
      },
    ],
  },
  {
    type: "groupHeader",
    groupTitle: "REFUND MANAGEMENT",
  },

  {
    id: "refund",
    title: "Refund Requests",
    type: "collapse",
    icon: <FaRegFileAlt color="blue" size={15} />,
    children: [
      {
        id: "pending",
        title: "Pending",
        type: "item",
        icon: <FaCircle color="yellow" size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/refundrequest/pendingRequest",
      },
      {
        id: "approv",
        title: "Approved",
        type: "item",
        icon: <FaCircle color="green" size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/refundrequest/approvedRequest",
      },
      {
        id: "refund request",
        title: "Refunded",
        type: "item",
        icon: <FaCircle color="green" size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/refundrequest/refundRequest",
      },
      {
        id: "reject",
        title: "Rejected",
        type: "item",
        icon: <FaCircle color="red" size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/refundrequest/rejectedRequest",
      },
    ],
  },

  {
    type: "groupHeader",
    groupTitle: "PRODUCT Managment",
  },
  {
    id: "PRODUCT MANAGEMENT",
    title: "Products",
    type: "item",
    icon: <FaRegFileAlt color="blue" size={15} />,
    permissions: ["admin", "editor"],
    // navLink: "/app/freshlist/hub/addproduct",
    navLink: "/app/freshlist/house/houseProductList",
  },
  {
    id: "PRODUCT REVIEWS",
    title: "Product Reviews",
    type: "item",
    icon: <Icon.Star fill="yellow" size={15} />,
    permissions: ["admin", "editor"],
    navLink: "/app/freshlist/customer/customerReview",
  },

  // {
  //   type: "groupHeader",
  //   groupTitle: "HUB Managment",
  // },
  // {
  //   id: "business section",
  //   title: "BUSSINESS SECTION",
  //   type: "collapse",
  //   icon: <FaStore size={15} />,
  //   children: [
  //     {
  //       id: "batch",
  //       title: "Assign to Hub",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/hub/assigntohub",
  //     },
  //     // {
  //     //   id: "addProduct",
  //     //   title: "Add Product",
  //     //   type: "item",
  //     //   icon: <FaCircle size={8} />,
  //     //   permissions: ["admin", "editor"],
  //     //   navLink: "/app/freshlist/hub/addproduct",
  //     // },
  //     // {
  //     //   id: "createbatch",
  //     //   title: " Create Batch ",
  //     //   type: "item",
  //     //   icon: <FaCircle size={8} />,
  //     //   permissions: ["admin", "editor"],
  //     //   navLink: "/app/freshlist/hub/createbatch",
  //     // },
  //     // {
  //     //   id: "assigntobatch",
  //     //   title: "Assign to Batch",
  //     //   type: "item",
  //     //   icon: <FaCircle size={8} />,
  //     //   permissions: ["admin", "editor"],
  //     //   navLink: "/app/freshlist/hub/assigntobatch",
  //     // },
  //   ],
  // },
  {
    type: "groupHeader",
    groupTitle: "PROMOTION MANAGEMENT",
  },
  {
    id: "PROMOTION MANAGEMENT",
    title: "Offers and Deals",
    type: "collapse",
    icon: <FaStore color="orange" size={15} />,
    children: [
      {
        id: "batchddd",
        title: "Coupons",
        type: "item",
        icon: <FaCircle color="blue" size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/coupon/couponList",
      },
      {
        id: "addProduct",
        title: "Add Product",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/hub/addproduct",
      },
      // {
      //   id: "createbatch",
      //   title: " Create Batch ",
      //   type: "item",
      //   icon: <FaCircle size={8} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/freshlist/hub/createbatch",
      // },
      // {
      //   id: "assigntobatch",
      //   title: "Assign to Batch",
      //   type: "item",
      //   icon: <FaCircle size={8} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/freshlist/hub/assigntobatch",
      // },
    ],
  },
  {
    type: "groupHeader",
    groupTitle: "Reports and analysis",
  },
  {
    id: "report sales",
    title: "Sales Report",
    type: "collapse",
    icon: <FaStore color="blue" size={15} />,
    children: [
      {
        id: "batch",
        title: "Product Report ",
        type: "item",
        icon: <FaCircle color="green" size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/report/productReport",
      },
      {
        id: "batch sales report",
        title: "Sales Report",
        type: "item",
        icon: <FaCircle color="green" size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/report/saleReport",
      },
      {
        id: "addProduct",
        title: "Order Report",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/customer/orderHistory",
      },
    ],
  },
  {
    type: "groupHeader",
    groupTitle: "BUSINESS SECTION",
  },
  {
    id: "business report",
    title: "Business Reports",
    type: "collapse",
    icon: <FaStore size={15} />,
    children: [
      {
        id: "batch",
        title: "Withdrawl Report ",
        type: "item",
        icon: <Icon.List color="green" size={14} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/vendor/withDraws",
      },
      {
        id: "batch bank report",
        title: "myBank Report",
        type: "item",
        icon: <Icon.Anchor size={14} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/hub/assigntohub",
      },
      {
        id: "addProduct",
        title: "Myshop Report",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/ecommerce/shop",
      },
    ],
  },

  // {
  //   type: "groupHeader",
  //   groupTitle: "Language",
  // },
  // {
  //   id: "language",
  //   title: "Language",
  //   type: "item",
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/language/LanguagesList",
  // },
];
export default navigationConfig;
